---
- name: "netconsd | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "netconsd | Include packages tasks"
  ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "lookup('ansible.builtin.vars', 'netconsd', default='')
      not in ['', [], '[]', None]"
    - "lookup('ansible.builtin.vars', 'netconsd') |
       community.general.json_query(lookup('ansible.builtin.vars',
      'netconsd_install_package', default='')) == 'true'"
  vars:
    netconsd_install_package: "[] | map(&install_package || 'false', @) | [0]"
- name: "netconsd | Include deployment tasks"
  ansible.builtin.import_tasks:
    file: "deploy.yml"
